apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial
  labels:
    app: factorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorial
  template:
    metadata:
      labels:
        app: factorial
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: factorial-container
          image: makrus1/factorial:latest
          ports:
            - containerPort: 8080
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /?number=1
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /?number=1
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
