apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-factorial
  namespace: minikube-factorial
  labels:
    app: minikube-factorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-factorial
  template:
    metadata:
      labels:
        app: minikube-factorial
    spec:
      restartPolicy: Always
      containers:
        - name: minikube-factorial
          image: minikube-factorial:0.0.1
          imagePullPolicy: Never
