name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login
        uses: docker/login-action@v2
        with:
          username: makrus1
          password: Maks200314
      - name: Buil and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: makrus1/factorial:latest
