name: Check
on: push
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make
        run: make -C src
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checout@v3
      - name: Test
        run: make -C src test && usr/bin/factorial_test
